### ISSUE TITLE
fix: zero out dead adventurers gold balances

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/loot-survivor#75] opened 2023-05-28 03:14 UTC
Dead adventurers gold balances should be cleared, otherwise the market includes this balance when calculating how many items to create

**Comment by starknetdev** [comment] 2023-05-30 15:03
@loothero I thought we added this but I can't actually see it in the code, do you know if/where it is?

**Comment by loothero** [comment] 2023-06-03 03:23
Closing this as a duplicate of https://github.com/BibliothecaDAO/realms-contracts/issues/355 which I'll have fixed shortly

**Closed by loothero** 2023-06-03 03:23 UTC
Labels: V1 Tweak
